version: 0.2

env:
  variables:
    CI: "true"
    NG_CLI_ANALYTICS: "false"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm ci --no-audit --no-fund
  build:
    commands:
      - bash scripts/validate.sh

cache:
  paths:
    - /root/.npm/**/*
